name: CI

on: [ push, pull_request ]

jobs:
    test:
        name: PHPUnit Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction

            -   name: Run tests
                run: make test

    ecs:
        name: Easy Coding Standard
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction

            -   name: Run ECS
                run: make ecs_check

    phpstan:
        name: PHPStan Analysis
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction

            -   name: Run PHPStan
                run: make phpstan